apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: basta-frontend
  namespace: aura
  labels:
    team: aura
spec:
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules: []
      external:
      {{#each external-hosts}}
        - host: "{{ this }}" 
      {{/each}}
  image: {{ image }}
  port: 8080 
  liveness:
    path: /isalive
  readiness:
    path: /isalive
  prometheus:
    path: /metrics
  replicas:
    min: 2
    max: 2
  ingresses: 
    {{#each ingress}}
    - "{{ this }}"
    {{/each}}
  envFrom:
    - secret: basta-secrets
  env:
{{#each envs}}
    - name: "{{name}}"
      value: "{{value}}"
{{/each}}
  skipCaBundle: true
  resources:
    limits:
      cpu: 500m 
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
