apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: basta-frontend-dev
  namespace: aura
  labels:
    team: aura
spec:
  azure:
    application:
      enabled: true
      tenant: nav.no
      replyURLs: 
        - "https://basta.dev.intern.nav.no/auth/openid/callback"
      claims:
        groups:
          - id: 
            - "47204455-7930-4eda-af04-cd2e91825651" 
            - "af129fd3-0d95-41a6-adc5-d3aa5a6c9ed6"
            - "84eb3bc1-fdac-4133-89e1-cafc8c75fa09"
            - "df17de8a-e293-4253-96f3-46544e57cc5a"
            - "c10e6466-4d28-4467-8e93-43cacfbcff92"
  accessPolicy:
    outbound:
      rules: []
      external:
      {{#each external-hosts}}
        - host: "{{ this }}" 
      {{/each}}
  image: {{ image }}
  port: 8080 
  liveness:
    path: /isalive
  readiness:
    path: /isalive
  prometheus:
    path: /metrics
  replicas:
    min: 2
    max: 2
  ingresses: 
    {{#each ingress}}
    - "{{ this }}"
    {{/each}}
  envFrom:
    - secret: basta-secrets
  env:
{{#each envs}}
    - name: "{{name}}"
      value: "{{value}}"
{{/each}}
  skipCaBundle: true
  resources:
    limits:
      cpu: 500m 
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
