# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    environment:
      EMAIL: noreply@nav.no
      GIT_AUTHOR_NAME: CircleCI
      GIT_COMMITTER_NAME: CircleCI
    docker:
      # specify the version you desire here
      - image: circleci/node:10.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - setup_remote_docker
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      #- run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      #- run: npm test
      #- run:
      #    name: Build docker image
      #    command: docker build -t navikt/basta-frontend:canary .
      #- run:
      #    name: Login to Dockerhub
      #    command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
      - run:
          name: 'Release, tag and build Docker'
          environment:
            CURRENT_VERSION: $(npm version | grep basta-frontend | cut -d"'" -f4 | cut -d"." -f1)
            BANAN: KAKe
          command: |
            echo $BANAN
            echo $CURRENT_VERSION
            version=$(npm version | grep basta-frontend | cut -d"'" -f4 | cut -d"." -f1)
            newVersion=$((version+1))
            semVer="$newVersion.0.0"
            #npm version $semVer
            #echo $semver
            #git commit -am "Setting release version $semVer [skip ci]" .
            #git tag -a basta-frontend-${semVer} -m 'basta-frontend-${semVer}'
            #git push  --set-upstream https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@github.com/navikt/basta-frontend.git --tags"
            #git push  --set-upstream https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@github.com/navikt/basta-frontend.git master"
            #docker build -t navikt/basta-frontend:$semVer .
            #docker push navikt/basta-frontend:$semVer
