version: 2.1

orbs:
    nais-deployment: navikt/nais-deployment@1.3.0

references:
    container_config: &container_config
        docker:
            - image: circleci/node:10.9
        working_directory: ~/frontend

workspace_root: &workspace_root /tmp/workspace

restore_source: &restore_source
    restore_cache:
        keys:
            - v1-repo-{{ .Branch }}-{{ .Revision }}

restore_node_modules: &restore_node_modules
    restore_cache:
        keys:
        - v1-dependencies-node-{{ checksum "package.json" }}

attach_workspace: &attach_workspace
    attach_workspace:
        at: *workspace_root

read_environment_variables: &read_environment_variables
    run:
        name: Set up environment variables
        command: cat /tmp/workspace/properties.env >> $BASH_ENV


jobs:
    checkout_code:
        <<: *container_config
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints: 
                    - '01:47:91:7b:1c:26:c3:bb:de:ac:1f:3b:78:94:c6:55'
            - run:
                name: 'Checkout aura-infra repo'
                command: git clone git@github.com:navikt/aura-infra.git
            - save_cache:
                key: v1-repo-{{ .Branch }}-{{ .Revision }}
                paths:
                    - .

    build_and_test:
        <<: *container_config
        steps:
            - *restore_source
            - run: npm install
            - save_cache:
                key: v1-dependencies-node-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run: npm test

    generate_version_number:
        <<: *container_config
        steps:
        - *restore_source
        - run:
            name: 'Generate version number'
            command: |
                mkdir /tmp/workspace
                export VERSION=$(date "+%Y-%m-%d")-$(git --no-pager log -1 --pretty=%h)
                echo "export VERSION=\"$VERSION\"" >> /tmp/workspace/properties.env
        - persist_to_workspace:
            root: *workspace_root
            paths:
                - properties.env

    release:
        <<: *container_config
        steps:
            - *restore_source
            - *restore_node_modules
            - *attach_workspace
            - *read_environment_variables
            - setup_remote_docker:
                docker_layer_caching: true
            - run:
                name: Login to GPR
                command: echo "$GPR_PASSWORD" | docker login -u "$GPR_USER" --password-stdin docker.pkg.github.com
            - run:
                name: Build and push docker image
                command: |
                    docker build -t docker.pkg.github.com/navikt/basta-frontend/basta-frontend:${VERSION} .
                    docker push docker.pkg.github.com/navikt/basta-frontend/basta-frontend:${VERSION}
    
    deploy_to_dev:
        docker:
            - image: 'navikt/deployment-cli:v0.2.0'
        steps:
            - *restore_source
            - *attach_workspace
            - *read_environment_variables
            - run: 
                name: LS
                command: ls -la 
            - run:
                name: deploy to dev-gcp
                command: | 
                    deployment-cli deploy create --cluster=dev-gcp --repository=navikt/basta-frontend --team aura --resource=aura-infra/basta-frontend/dev-gcp/nais.yaml --var version=${VERSION} --appid=21324 --key=aura-infra/deployment-keys/github.key.pem.enc
        
workflows:
    build_and_release:
        jobs:
            - checkout_code
            - build_and_test:
                requires:
                    - checkout_code
            - generate_version_number:
                filters:
                    branches:
                        only: master
                requires:
                    - build_and_test
            - release:
                filters:
                    branches:
                        only: master
                requires:
                    - generate_version_number
            - deploy_to_dev:
                filters:
                    branches:
                        only: master
                requires:
                    - release