version: 2.1
orbs:
  nais-deployment: navikt/nais-deployment@1.1.1
jobs:
  build_and_test:
    environment:
      EMAIL: noreply@nav.no
    docker:
      - image: circleci/node:10.9
    working_directory: ~/repo

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'e2:70:a3:2f:ce:7a:56:53:02:b5:56:b2:4d:c4:ea:dc'

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

  release:
    docker:
      - image: circleci/node:10.9
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to Dockerhub
          command: echo "$GPR_PASSWORD" | docker login -u "$GPR_USER" --password-stdin docker.pkg.github.com
      - run:
          name: 'Release, tag and build Docker'
          command: |
            mkdir /tmp/workspace
            export VERSION="$(date '+%Y-%m-%d')-$(git --no-pager log -1 --pretty=%h)"
            echo "export VERSION="$VERSION" >> /tmp/workspace/properties.env
            echo $VERSION
            docker build -t docker.pkg.github.com/navikt/basta-frontend/basta-frontend:$VERSION .
            docker push docker.pkg.github.com/navikt/basta-frontend/basta-frontend:$VERSION
            #git clone git@github.com:navikt/nais-yaml.git && cd nais-yaml
            #sed -i 's/version.*/version\: '"${VERSION}"'/g' vars/basta-frontend.yaml
            #git commit -am "Update basta-frontend to ${VERSION}"
            #git push origin master

workflows:
  build_and_release:
    jobs:
      - build_and_test
      - release:
          filters:
            branches:
              only: master
          requires:
            - build_and_test
      #-nais/deploy:
      #  repo: navikt/basta-frontend
      #  image: docker.pkg.github.com/navikt/basta-frontend/basta-frontend
      #github-app-id: 1234
      #  nais-template: nais.yaml
      #  environment: dev-gcp
      #  team: aura
