# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - setup_remote_docker
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
      - run:
          name: Copy files for Docker image
          command: |
            mkdir -p /docker/dist
            cp -r api/src /docker/dist
            cd /docker/dist && cp ../../package.json . && npm install --production && cd -
            npm install && npm run build || exit 1
            cp -r dist /docker/dist
            cp Dockerfile ./docker
      - run:
          name: Login to Dockerhub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
      - run:
          name: Build Docker container
          command: docker build -t navikt/basta-frontend:canary .
      - run:
          name: Push canary Docker container
          command: docker push navikt/basta-frontend:canary
