# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    environment:
      EMAIL: noreply@nav.no
      GIT_AUTHOR_NAME: CircleCI
      GIT_COMMITTER_NAME: CircleCI
    docker:
      # specify the version you desire here
      - image: circleci/node:10.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo

    steps:
      - setup_remote_docker
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
      - run:
          name: Build docker image
          command: docker build -t navikt/basta-frontend:canary .
      - run:
          name: Login to Dockerhub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
      - run:
          name: 'Release, tag and build Docker'
          command: |
            export VERSION=$(npm version | grep basta-frontend | cut -d"'" -f4 | cut -d"." -f1)
            export NEW_VERSION=$((VERSION+1))
            export SEM_VER="$NEW_VERSION.0.0"
            npm version $SEM_VER
            git commit -am "Setting release version $SEM_VER [skip ci]" .
            git tag -a basta-frontend-$SEM_VER -m 'basta-frontend-$SEM_VER'
            git push  --set-upstream https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@github.com/navikt/basta-frontend.git --tags"
            git push  --set-upstream https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@github.com/navikt/basta-frontend.git master"
            docker build -t navikt/basta-frontend:$SEM_VER .
            docker push navikt/basta-frontend:$SEM_VER
