export const SUBMIT_OPERATION = 'SUBMIT_OPERATION'
export const OPERATION_SUBMITTING = 'OPERATION_SUBMITTING'
export const OPERATION_SUBMIT_SUCCESSFUL = 'OPERATION_SUBMIT_SUCCESSFUL'
export const OPERATION_SUBMIT_FAILED = 'OPERATION_SUBMIT_FAILED'

export const CREDENTIAL_LOOKUP_REQUEST = 'CREDENTIAL_LOOKUP_REQUEST'
export const CREDENTIAL_LOOKUP_SUBMITTING = 'CREDENTIAL_LOOKUP_SUBMITTING'
export const CREDENTIAL_LOOKUP_SUCCESSFUL = 'CREDENTIAL_LOOKUP_SUCCESSFUL'
export const CREDENTIAL_LOOKUP_FAILED = 'CREDENTIAL_LOOKUP_FAILED'
