// INITALIZE APP
export const INITIALIZE_APPLICATION = 'INITIALIZE_APPLICATION'
export const APPLICATION_READY = 'APPLICATION_READY'

// HISTORY
export const HISTORY_REQUEST = 'HISTORY_REQUEST'
export const HISTORY_FETCHING = 'HISTORY_FETCHING'
export const HISTORY_RECEIVED = 'HISTORY_RECEIVED'
export const HISTORY_COMPLETE = 'HISTORY_COMPLETE'
export const HISTORY_REQUEST_FAILED = 'HISTORY_REQUEST_FAILED'

// FILTERS
export const HISTORY_APPLY_FILTER = 'HISTORY_APPLY_FILTER'
export const HISTORY_APPLY_FILTER_COMPLETE = 'HISTORY_APPLY_FILTER_COMPLETE'
export const HISTORY_APPLY_FILTER_PROCESSING = 'HISTORY_APPLY_FILTER_PROCESSING'

// REFRESH ORDERLIST AFTER NEW ORDER/OPERATION
export const LATEST_ORDER_REQUEST = 'LATEST_ORDER_REQUEST'
export const LATEST_ORDER_FETCHING = 'LATEST_ORDER_FETCHING'
export const LATEST_ORDER_RECEIVED = 'LATEST_ORDER_RECEIVED'
export const LATEST_ORDER_REQUEST_FAILED = 'LATEST_ORDER_REQUEST_FAILED'

// USER
export const TOGGLE_NAVMENU = 'TOGGLE_NAVMENU'
export const CLOSE_NAVMENU = 'CLOSE_NAVMENU'

// SESSION
export const USER_SESSION_ACTIVE = 'USER_SESSION_ACTIVE'
export const USER_SESSION_EXPIRED = 'USER_SESSION_EXPIRED'

// USER
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_FETCHING = 'USER_PROFILE_FETCHING'
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED'
export const USER_PROFILE_REQUEST_FAILED = 'USER_PROFILE_REQUEST_FAILED'
export const USER_LOGOUT = 'USER_LOGOUT'

/**
 * FORM DATA
 */
export const ENVIRONMENTS_REQUEST = 'ENVIRONMENTS_REQUEST'
export const ENVIRONMENTS_FETCHING = 'ENVIRONMENTS_FETCHING'
export const ENVIRONMENTS_RECEIVED = 'ENVIRONMENTS_RECEIVED'
export const ENVIRONMENTS_REQUEST_FAILED = 'ENVIRONMENTS_REQUEST_FAILED'

export const APPLICATIONS_REQUEST = 'APPLICATIONS_REQUEST'
export const APPLICATIONS_FETCHING = 'APPLICATIONS_FETCHING'
export const APPLICATIONS_RECEIVED = 'APPLICATIONS_RECEIVED'
export const APPLICATIONS_REQUEST_FAILED = 'APPLICATIONS_REQUEST_FAILED'

export const RESOURCES_REQUEST = 'RESOURCES_REQUEST'
export const RESOURCES_FETCHING = 'RESOURCES_FETCHING'
export const RESOURCES_RECEIVED = 'RESOURCES_RECEIVED'
export const RESOURCES_REQUEST_FAILED = 'RESOURCES_REQUEST_FAILED'

export const SCOPED_RESOURCE_REQUEST = 'SCOPED_RESOURCE_REQUEST'
export const SCOPED_RESOURCE_FETCHING = 'SCOPED_RESOURCE_FETCHING'
export const SCOPED_RESOURCE_RECEIVED = 'SCOPED_RESOURCE_RECEIVED'
export const SCOPED_RESOURCE_REQUEST_FAILED = 'SCOPED_RESOURCE_REQUEST_FAILED'

export const MQCLUSTERS_REQUEST = 'MQCLUSTERS_REQUEST'
export const MQCLUSTERS_FETCHING = 'MQCLUSTERS_FETCHING'
export const MQCLUSTERS_RECEIVED = 'MQCLUSTERS_RECEIVED'
export const MQCLUSTERS_REQUEST_FAILED = 'MQCLUSTERS_REQUEST_FAILED'

export const DBTEMPLATES_REQUEST = 'DBTEMPLATES_REQUEST'
export const DBTEMPLATES_FETCHING = 'DBTEMPLATES_FETCHING'
export const DBTEMPLATES_RECEIVED = 'DBTEMPLATES_RECEIVED'
export const DBTEMPLATES_REQUEST_FAILED = 'DBTEMPLATES_REQUEST_FAILED'

export const VIRTUALSERVERS_REQUEST = 'VIRTUALSERVERS_REQUEST'
export const VIRTUALSERVERS_FETCHING = 'VIRTUALSERVERS_FETCHING'
export const VIRTUALSERVERS_RECEIVED = 'VIRTUALSERVERS_RECEIVED'
export const VIRTUALSERVERS_REQUEST_FAILED = 'VIRTUALSERVERS_REQUEST_FAILED'

export const CERTIFICATE_FASIT_REQUEST = 'CERTIFICATE_FASIT_REQUEST'
export const CERTIFICATE_FASIT_RECEIVED = 'CERTIFICATE_FASIT_RECEIVED'
export const CERTIFICATE_FASIT_REQUEST_FAILED = 'CERTIFICATE_FASIT_REQUEST_FAILED'
export const CERTIFICATE_FASIT_RESET = 'CERTIFICATE_FASIT_RESET'

export const CREDENTIAL_LOOKUP_REQUEST = 'CREDENTIAL_LOOKUP_REQUEST'
export const CREDENTIAL_LOOKUP_SUBMITTING = 'CREDENTIAL_LOOKUP_SUBMITTING'
export const CREDENTIAL_LOOKUP_SUCCESSFUL = 'CREDENTIAL_LOOKUP_SUCCESSFUL'
export const CREDENTIAL_LOOKUP_FAILED = 'CREDENTIAL_LOOKUP_FAILED'
export const CREDENTIAL_LOOKUP_RESET = 'CREDENTIAL_LOOKUP_RESET'

export const CUSTOM_CREDENTIAL_LOOKUP_REQUEST = 'CUSTOM_CREDENTIAL_LOOKUP_REQUEST'

/**************
 * ORDER
 *************/
// ORDER FORM
export const SUBMIT_FORM = 'SUBMIT_FORM'
export const FORM_SUBMITTING = 'FORM_SUBMITTING'
export const FORM_SUBMIT_SUCCESSFUL = 'FORM_SUBMIT_SUCCESSFUL'
export const FORM_SUBMIT_FAILED = 'FORM_SUBMIT_FAILED'
export const RESET_FORM = 'RESET_FORM'

// STATUSLOG
export const STATUSLOG_REQUEST = 'STATUSLOG_REQUEST'
export const STATUSLOG_FETCHING = 'STATUSLOG_FETCHING'
export const STATUSLOG_RECEIVED = 'STATUSLOG_RECEIVED'
export const STATUSLOG_REQUEST_FAILED = 'STATUSLOG_REQUEST_FAILED'

// ORDER
export const ORDER_REQUEST = 'ORDER_REQUEST'
export const ORDER_FETCHING = 'ORDER_FETCHING'
export const ORDER_RECEIVED = 'ORDER_RECEIVED'
export const ORDER_REQUEST_FAILED = 'ORDER_REQUEST_FAILED'

/**********************
 * OPERATIONS
 *********************/
export const SUBMIT_OPERATION = 'SUBMIT_OPERATION'
export const OPERATION_SUBMITTING = 'OPERATION_SUBMITTING'
export const OPERATION_SUBMIT_SUCCESSFUL = 'OPERATION_SUBMIT_SUCCESSFUL'
export const OPERATION_SUBMIT_FAILED = 'OPERATION_SUBMIT_FAILED'

/************************
 * NOTIFICATION
 ***********************/
export const POST_NOTIFICATION = 'POST_NOTIFICATION'
export const POST_NOTIFICATION_SUBMITTING = 'POST_NOTIFICATION_SUBMITTING'
export const POST_NOTIFICATION_SUCCESSFUL = 'POST_NOTIFICATION_SUCCESSFUL'
export const POST_NOTIFICATION_FAILED = 'POST_NOTIFICATION_FAILED'
export const NOTIFICATIONS_REQUEST = 'NOTIFICATIONS_REQUEST'
export const ACTIVE_NOTIFICATIONS_RECEIVED = 'ACTIVE_NOTIFICATIONS_RECEIVED'
export const NOTIFICATIONS_REQUEST_FAILED = 'NOTIFICATIONS_REQUEST_FAILED'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'
export const REMOVE_NOTIFICATION_FAILED = 'REMOVE_NOTIFICATION_FAILED'
