name: 'Build and deploy basta-frontend'

on: push

env:
  TEAM: team-atom

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: ${{ env.TEAM }}
          tag: ${{ github.sha }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    name: Deploy to dev-gcp
    needs: build
    #if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/naiserator-dev.yml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: .nais/dev-config.json
  deploy-prod:
    name: Deploy to prod-gcp
    needs:
      - build
      - deploy-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/naiserator.yml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: .nais/prod-config.json
